version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:12
jobs:
  prepare-deps:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: yarn
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  test:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: yarn test
  release:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run release
          command: yarn run semantic-release
workflows:
  version: 2
  build_and_test:
    jobs:
      - prepare-deps
      - test:
          requires:
            - prepare-deps
      - release:
          requires:
            - test
